baseURL: https://hb-theme.hugomods.com/
title: HB Theme Template
# Copyright, the {year} is the placeholder of this year.
copyright: "Copyright Â© 2022-{year} [Hugo Modules](https://hugomods.com) and [Hugo Bootstrap Framework](https://hb.hugomods.com). All Rights Reserved."
defaultContentLanguage: en
defaultContentLanguageInSubdir: true # disable this to remove the default language code from URL, i.e. /en/docs -> /docs. 
disqusShortname: hb-site
enableRobotsTXT: true

permalinks:
  blog: /blog/:year/:month/:title

module:
  # For some regions can not access the proxy.golang.org, i.e. China.
  # proxy: https://goproxy.cn,https://goproxy.io,https://mirrors.aliyun.com/goproxy,direct

  # The order of module is very important, precedence from top to bottom.
  imports:
    # syntax highlighting, see https://hb.hugomods.com/en/docs/modules/syntax-highlighting/.
    # - path: github.com/hbstack/syntax-highlighting/styles/github-dark
  
    # icons modules
    - path: github.com/hugomods/icons/vendors/font-awesome
    # - path: github.com/hugomods/icons/vendors/mdi
    # - path: github.com/hugomods/icons/vendors/simple-icons
    # - path: github.com/hugomods/icons/vendors/tabler
    # - path: github.com/hugomods/icons/vendors/feather

    # blog comments engine
    - path: github.com/hbstack/blog/modules/giscus
    # - path: github.com/hbstack/blog/modules/disqus
    # - path: github.com/hbstack/blog/modules/utterances

    # blog content panel
    - path: github.com/hbstack/blog/modules/content-panel

    # docs comments engine
    - path: github.com/hbstack/docs/modules/giscus
    # - path: github.com/hbstack/docs/modules/utterances
    # - path: github.com/hbstack/docs/modules/disqus

    # docs content panel
    - path: github.com/hbstack/docs/modules/content-panel

    # other modules
    # - path: github.com/hugomods/google-analytics
    # - path: github.com/hugomods/google-adsense

    # recommended modules
    - path: github.com/hbstack/meta/recommended

outputs:
  home:
    - HTML
    - Offline
    - RSS
    - SearchIndex
    - WebAppManifest

taxonomies:
  authors: authors
  tags: tags
  categories: categories
  series: series

build:
  writeStats: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false
